version: 2.1

orbs:
  maven: circleci/maven@0.0.12

executorType: machine

jobs:
  compile:
    steps:
      - checkout
      - run: mvn -B compile -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-blueprint-microservices-{{ checksum "pom.xml" }}
  unit-test:
    steps:
      - checkout
      - restore_cache:
          key: circleci-blueprint-microservices-{{ checksum "pom.xml" }}
      - run: mvn -B test
  integration-test:
    steps:
      - checkout
      - restore_cache:
          key: circleci-blueprint-microservices-{{ checksum "pom.xml" }}
      - run: mvn -B verify

workflows:
  compile_tests:
    jobs:
      - compile
      - unit-test
      - integration-test