version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  compile:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn -B compile -DskipTests
  unit-test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn -B test
  integration-test:
    machine: true
    steps:
      - checkout
      - run: mvn -B verify

workflows:
  compile_tests:
    jobs:
      - compile
      - unit-test:
          requires:
            - compile
      - integration-test:
          requires:
            - unit-test