version: 2.1

orbs:
  maven: circleci/maven@0.0.12

dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

workflows:
  maven_test:
    jobs:
      - maven/test
